security:
    providers:
        in_memory:
            memory: ~
        hwi:
            id: app.user.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: true
            oauth:
                resource_owners:
                    my_github: "/login/check-github"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                check_path: /login
                oauth_user_provider:
                    service: app.user.provider
            logout:
              target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

